version: 1
update_configs:
  - package_manager: "javascript"
    version_requirement_updates: "increase_versions"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "mocha"
      - match:
          dependency_name: "chai"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "music-metadata"
      - match:
          dependency_name: "strtok3"
      - match:
          dependency_name: "@types/chai"
      - match:
          dependency_name: "coveralls"
      - match:
          dependency_name: "music-metadata-browser"
      - match:
          dependency_name: "nyc"
